### ISSUE TITLE
Build from image

### ISSUE THREAD

**Issue by htbase** [kadimasolutions/docker-plugin_lizardfs#1]
Hi there

Thanks for all the work

Wondering if there is any info or documentation already on how to create the plugin from source

Thanks
Bruno

**Comment by zicklag** [comment]
Hi @htbase, I have instructions on how to build in in the [README](https://github.com/kadimasolutions/docker-plugin_lizardfs#building-the-plugin). That tells you how to build the plugin as a Docker managed plugin.

If you want to build the normal container that is used for the swarm deployment then you just have to run a `docker build -t container-tag .` in the project root.

Just a heads up, I am planning on greatly refactoring the swarm deployment hopefully sometime in the near future if I can get to it. :) When I do that, the plugin will be installed the on a swarm with a Docker managed plugin like it is for a single node.

**Comment by htbase** [comment]
Thanks!

We can build the plugin and use it

Only “weird” behaviour is that when we do a mount using the volume name created by the plugin (docker run -it --rm -v dockervol1:/mnt/data ubuntu), it mounts the whole root directory instead of only the folder created for the volume

**Comment by htbase** [comment]
Thanks!

We can build the plugin and use it

Only “weird” behaviour is that when we do a mount using the volume name created by the plugin (docker run -it --rm -v dockervol1:/mnt/data ubuntu), it mounts the whole storage root directory instead of only the folder created for the volume

**Comment by zicklag** [comment]
Did you happen to specify the `ROOT_VOLUME_NAME` when you installed the plugin. I always use that option so I may have missed bugs that occur when you don't specify it.

**Comment by zicklag** [comment]
Closing this now. You can open a new issue if you still have problems with it.
